### PR TITLE
fix: defer Role.setup() until agent is registered with a container

### PR DESCRIPTION
**Pull request by maurerle**
Before this change, calling add_role() on a `RoleAgent` before registering it with a container would call setup() immediately with a half-initialized context: no scheduler, no container, and self.context.addr crashing with:

    AttributeError: 'NoneType' object has no attribute '_container'

Any role that scheduled tasks or accessed addr/current_timestamp in setup() would silently fail or crash.

To resolve this without altering the synchronous execution and coordination logic of setup() (which is required by composition helpers like agent_composed_of), the fix adds a None-check for context before dereferencing _container in AgentDelegates.addr:

    if self.context is None or self.context._container is None:
        return None

A new test case is added to verify that setup() runs immediately upon adding a role, and that shared model coordination (like in agent_composed_of) works during setup without crashing.

This behavior was introduced in fa27662

### CODE REVIEW

**Review by rcschrg — CHANGES_REQUESTED** [review]
Check Ruff linting, otherwise nice finding. 

I am actually wondering that this has never come up before, as the general problem that the context is half-initialized before registration was always present.

**Comment by maurerle** [comment]
It somehow was not an issue before v2.2.0:
https://github.com/assume-framework/assume/actions/runs/29564850471/job/87835063237?pr=840

Occured in our tests however :)

**Comment by maurerle** [comment]
I adjusted the patch as the doctest was failing. So I do think that the small check should be enough

**Review by rcschrg — APPROVED** [review]

**Comment by maurerle** [comment]
@rcschrg can we get a v2.2.1 release with this fix?
I can take care of it, if we are fine with it :)
